### ISSUE TITLE
Add Proxy Authentication!

### ISSUE THREAD

**Issue by elbiozard** [Mon-ius/Docker-Warp-Socks#10]
Hello, very good job!
Could the possibility of authenticating the proxy connection with username and password be added? If I didn't see wrong, Danted is used and I think it can be done but I don't know how to do it. Perhaps it would be very good to be able to add them as a parameter (username and password) when docker-compose is built.

**Comment by Mon-ius** [comment]
Hi Elbiozard,

Thank you for your suggestion. As mentioned in the `1.2 🔧 Pre-Configuration Start (advanced)` section, you may add your own authentication for danted by mapping the configuration file. For reference on the danted configuration file for authentication, we recommend visiting https://www.inet.no/dante/doc/latest/config/auth.html 😊.

If you have any ideas about adding parameters to automate the configuration file, we always welcome PRs from the community 🎉.
