### ISSUE TITLE
RTNETLINK error

### ISSUE THREAD

**Issue by f0ghua** [Mon-ius/Docker-Warp-Socks#11]
I meet this error when run docker-compose. My platform is ubuntu 18.04 TLS.
```
fog@Docker-Warp-Socks$ sudo /home/fog/bin/docker-compose up
Starting docker-warp-socks_warp-socks_1 ... done
Attaching to docker-warp-socks_warp-socks_1
warp-socks_1  | [#] ip link add warp type wireguard
warp-socks_1  | RTNETLINK answers: Operation not supported
warp-socks_1  | Unable to access interface: Protocol not supported
warp-socks_1  | [#] ip link delete dev warp
warp-socks_1  | Cannot find device "warp"
docker-warp-socks_warp-socks_1 exited with code 1
```
But with another pc, which also installed with the same linux os (different minor version, which is 18.04.4), it works fine.

**Comment by Mon-ius** [comment]
Hi, fOghua

Thanks for your report. Did you try the old way to check it?

Directly run with `Docker` instead of `docker-compose`

See https://github.com/Mon-ius/Docker-Warp-Socks/issues/6#issuecomment-1497602912
