### ISSUE TITLE
运行几天后sock5断连

### ISSUE THREAD

**Issue by iknow2333** [Mon-ius/Docker-Warp-Socks#12]
vps内部可以curl --proxy socks5h://127.0.0.1:9091 https://www.cloudflare.com/cdn-cgi/trace 访问成功，但是外部设备无法连接这个端口
![屏幕截图 2023-05-28 000309](https://github.com/Mon-ius/Docker-Warp-Socks/assets/103983460/5608cf0e-d6b2-4216-b798-7936b9f00297)
![屏幕截图 2023-05-28 000232](https://github.com/Mon-ius/Docker-Warp-Socks/assets/103983460/eefd40b6-a525-489d-9fe4-221f031b093f)

**Comment by Mon-ius** [comment]
You 2nd screenshot shows everything works fine, can u details the problem?
