### ISSUE TITLE
Is there any docker-compose example ?

### ISSUE THREAD

**Issue by padixa** [Mon-ius/Docker-Warp-Socks#17]
Something like this:

warp:

>     image: Mon-ius/Docker-Warp-Socks
>     container_name: warp
>     restart: unless-stopped
>     ports:
>       - '127.0.0.1:1918:1080'
>     environment:
>       - WARP_SLEEP=2
>       # - WARP_LICENSE_KEY= # optional
>     cap_add:
>       - NET_ADMIN
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=1
>       - net.ipv4.conf.all.src_valid_mark=1
>     volumes:
>       - ./warp:/var/lib/cloudflare-warp

And then we could put mdm.xml like warp folder, and write the settings like :

> <dict>
>   <key>organization</key>
>   <string>xx</string>  
>   <key>auth_client_id</key>
>   <string>xx</string>
>   <key>auth_client_secret</key>
>   <string>xx</string>
> </dict>

And finally we could access this network from other app, use some Environment in docker-compse for other app like:

> PROXY=socks5://warp:1080

**Comment by Mon-ius** [comment]
See #16 or uncommet `https://github.com/Mon-ius/Docker-Warp-Socks/blob/main/dev/warp-socks.yml`
