### ISSUE TITLE
Any chance of integrating a http proxy as well?

### ISSUE THREAD

**Issue by hacktek** [Mon-ius/Docker-Warp-Socks#18]
If you could integrate something like privoxy https://www.privoxy.org/ it'd be great since it would help support applications that do not support socks proxies.

**Comment by Mon-ius** [comment]
Hi @hacktek

Thanks for your feedback, actually the socks5 proxy can be easily integrated for HTTP/HTTPS proxy protocol

For example,
```bash
export http_proxy=socks5://127.0.0.1:9091
export https_proxy=$http_proxy
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
```
