### ISSUE TITLE
Docker安装昨天突然不能用了

### ISSUE THREAD

**Issue by internalG** [Mon-ius/Docker-Warp-Socks#19]
是里面有什么配置过期了吗？之前一直很稳定。除了socks无法连接看不到其他错误信息。

**Comment by catfishlty** [comment]
我也是同样的问题
Docker Image: https://hub.docker.com/layers/monius/docker-warp-socks/latest/images/sha256-4fcd9c812235afb64a498aa3fa9f2a7a0cbed005f29c55fcf9ab82cecf9bdd5b?context=explore

#### logs
```
curl: (52) Empty reply from server
/run/entrypoint.sh: line 15: wgcf: command not found
sed: can't read /opt/wgcf-profile.conf: No such file or directory
curl: (52) Empty reply from server
/run/entrypoint.sh: line 15: wgcf: command not found
sed: can't read /opt/wgcf-profile.conf: No such file or directory
curl: (28) Failed to connect to github.com port 443: Connection timed out
/run/entrypoint.sh: line 15: wgcf: command not found
sed: can't read /opt/wgcf-profile.conf: No such file or directory
curl: (18) transfer closed with 7009749 bytes remaining to read
/run/entrypoint.sh: line 15: wgcf: command not found
sed: can't read /opt/wgcf-profile.conf: No such file or directory
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
/run/entrypoint.sh: line 15: wgcf: command not found
sed: can't read /opt/wgcf-profile.conf: No such file or directory
curl: (52) Empty reply from server
/run/entrypoint.sh: line 15: wgcf: command not found
sed: can't read /opt/wgcf-profile.conf: No such file or directory
```

**Comment by Mon-ius** [comment]
will try to fix it soon, thx for notification

**Comment by Mon-ius** [comment]
Hey, @internalG @catfishlty 

I can confirm that the problem is located on the upstream, which mean we may cannot use `wgcf` to connect to `warp` network for free anymore.

I suggest to contact [ViRb3/wgcf](https://github.com/ViRb3/wgcf) first.

regards

**Comment by Mon-ius** [comment]
Dear All, 

Just found the root cause, see

- https://www.cloudflarestatus.com/incidents/hm7491k53ppg
- https://puck.nether.net/pipermail/outages/2023-November/014915.html
- https://news.ycombinator.com/item?id=38113503

In short, Cloudflare's main dc sucks and power off, now should be find.

**Comment by internalG** [comment]
Good catch! Will check back later.
