### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by Showfom** [Mon-ius/Docker-Warp-Socks#20]
```bash
Nov  2 19:35:03 (1698953703.002323) danted[153]: info: block(1): tcp/accept ]: 172.18.0.4.32900 172.18.0.2.9091: request was not performed due to error: could not resolve hostname "example.com": Temporary failure in name resolution
```

Temporary solution

Login to the container

```bash
docker exec -it opt-warp-socks-1 bash
```

and change DNS to `8.8.8.8` instead of `1.1.1.1`

```bash
cat > /etc/resolv.conf << EOF
nameserver 8.8.8.8
EOF
```

**Comment by Mon-ius** [comment]
Thanks for your report; 

Due to the Global Power off of Cloudflare, the warp service was thus influenced see https://www.cloudflarestatus.com/incidents/hm7491k53ppg

Plz keep trying in next week, keep report after CF recover the service :P

**Comment by intrapt** [comment]
I also had this issue, which seems to be the same as #8. I fixed it by regenerating wgcf-account.toml:

Logging into the container

```
docker exec -it warp-socks-1 bash
```
Regenerating wgcf-account.toml
```
rm wgcf-account.toml
wgcf register
```

**Comment by FDUZS** [comment]
Same here. And the solution offered by @Showfom works.

**Comment by Mon-ius** [comment]
Glad to see problems got fixed here, will keep this open for the sake of referencing future related issues  🤗

**Comment by Mon-ius** [comment]
update some new features today, and hope you enjoy 🤗
