### ISSUE TITLE
How to use warp+ with your project？

### ISSUE THREAD

**Issue by kokojacket** [Mon-ius/Docker-Warp-Socks#21]
I currently have the warp+ key, how can I use it through your project?

**Comment by kokojacket** [comment]
<img width="573" alt="1701394540523" src="https://github.com/Mon-ius/Docker-Warp-Socks/assets/74887370/4da47777-31cd-4ac1-af4e-ef7c354dade3">

**Comment by Mon-ius** [comment]
See https://github.com/Mon-ius/Docker-Warp-Socks#12--warp-plus-accountadvanced , will online soon
