### ISSUE TITLE
Issue on arm64 centos with latest docker Module ip6_tables not found in directory 

### ISSUE THREAD

**Issue by pvbhanuteja** [Mon-ius/Docker-Warp-Socks#23]
Tried docker compose 

[opc@instance-20240208-2225 dev]$ docker compose -f warp-socks.yml logs
warp-socks-1  | 2024/02/12 23:22:14 Using config file: wgcf-account.toml
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Device name   : 9CFD7F
warp-socks-1  | 2024/02/12 23:22:16 Device model  : PC
warp-socks-1  | 2024/02/12 23:22:16 Device active : true
warp-socks-1  | 2024/02/12 23:22:16 Account type  : free
warp-socks-1  | 2024/02/12 23:22:16 Role          : child
warp-socks-1  | 2024/02/12 23:22:16 Premium data  : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 Quota         : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Successfully created Cloudflare Warp account
warp-socks-1  | 2024/02/12 23:22:16 Using config file: wgcf-account.toml
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Device name   : 9CFD7F
warp-socks-1  | 2024/02/12 23:22:16 Device model  : PC
warp-socks-1  | 2024/02/12 23:22:16 Device active : true
warp-socks-1  | 2024/02/12 23:22:16 Account type  : free
warp-socks-1  | 2024/02/12 23:22:16 Role          : child
warp-socks-1  | 2024/02/12 23:22:16 Premium data  : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 Quota         : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Successfully generated WireGuard profile: wgcf-profile.conf
warp-socks-1  | [#] ip link add warp type wireguard
warp-socks-1  | [#] wg setconf warp /dev/fd/63
warp-socks-1  | [#] ip -4 address add 172.16.0.2/32 dev warp
warp-socks-1  | [#] ip -6 address add 2606:4700:110:8572:30f3:d37c:e33b:71dd/128 dev warp
warp-socks-1  | [#] ip link set mtu 1280 up dev warp
warp-socks-1  | [#] resolvconf -a warp -m 0 -x
warp-socks-1  | [#] wg set warp fwmark 51820
warp-socks-1  | [#] ip -6 route add ::/0 dev warp table 51820
warp-socks-1  | [#] ip -6 rule add not fwmark 51820 table 51820
warp-socks-1  | [#] ip -6 rule add table main suppress_prefixlength 0
warp-socks-1  | [#] ip6tables-restore -n
warp-socks-1  | modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/5.15.0-202.135.2.el8uek.aarch64
warp-socks-1  | ip6tables-restore v1.8.4 (legacy): ip6tables-restore: unable to initialize table 'raw'
warp-socks-1  | 
warp-socks-1  | Error occurred at line: 1
warp-socks-1  | Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
warp-socks-1  | [#] resolvconf -d warp -f
warp-socks-1  | [#] ip -6 rule delete table 51820
warp-socks-1  | [#] ip -6 rule delete table main suppress_prefixlength 0
warp-socks-1  | [#] ip link delete dev warp
[opc@instance-20240208-2225 dev]$ docker compose -f warp-socks.yml logs
warp-socks-1  | 2024/02/12 23:22:14 Using config file: wgcf-account.toml
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Device name   : 9CFD7F
warp-socks-1  | 2024/02/12 23:22:16 Device model  : PC
warp-socks-1  | 2024/02/12 23:22:16 Device active : true
warp-socks-1  | 2024/02/12 23:22:16 Account type  : free
warp-socks-1  | 2024/02/12 23:22:16 Role          : child
warp-socks-1  | 2024/02/12 23:22:16 Premium data  : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 Quota         : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Successfully created Cloudflare Warp account
warp-socks-1  | 2024/02/12 23:22:16 Using config file: wgcf-account.toml
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Device name   : 9CFD7F
warp-socks-1  | 2024/02/12 23:22:16 Device model  : PC
warp-socks-1  | 2024/02/12 23:22:16 Device active : true
warp-socks-1  | 2024/02/12 23:22:16 Account type  : free
warp-socks-1  | 2024/02/12 23:22:16 Role          : child
warp-socks-1  | 2024/02/12 23:22:16 Premium data  : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 Quota         : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Successfully generated WireGuard profile: wgcf-profile.conf
warp-socks-1  | [#] ip link add warp type wireguard
warp-socks-1  | [#] wg setconf warp /dev/fd/63
warp-socks-1  | [#] ip -4 address add 172.16.0.2/32 dev warp
warp-socks-1  | [#] ip -6 address add 2606:4700:110:8572:30f3:d37c:e33b:71dd/128 dev warp
warp-socks-1  | [#] ip link set mtu 1280 up dev warp
warp-socks-1  | [#] resolvconf -a warp -m 0 -x
warp-socks-1  | [#] wg set warp fwmark 51820
warp-socks-1  | [#] ip -6 route add ::/0 dev warp table 51820
warp-socks-1  | [#] ip -6 rule add not fwmark 51820 table 51820
warp-socks-1  | [#] ip -6 rule add table main suppress_prefixlength 0
warp-socks-1  | [#] ip6tables-restore -n
warp-socks-1  | modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/5.15.0-202.135.2.el8uek.aarch64
warp-socks-1  | ip6tables-restore v1.8.4 (legacy): ip6tables-restore: unable to initialize table 'raw'
warp-socks-1  | 
warp-socks-1  | Error occurred at line: 1
warp-socks-1  | Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
warp-socks-1  | [#] resolvconf -d warp -f
warp-socks-1  | [#] ip -6 rule delete table 51820
warp-socks-1  | [#] ip -6 rule delete table main suppress_prefixlength 0
warp-socks-1  | [#] ip link delete dev warp
[opc@instance-20240208-2225 dev]$ docker compose -f warp-socks.yml logs
warp-socks-1  | 2024/02/12 23:22:14 Using config file: wgcf-account.toml
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Device name   : 9CFD7F
warp-socks-1  | 2024/02/12 23:22:16 Device model  : PC
warp-socks-1  | 2024/02/12 23:22:16 Device active : true
warp-socks-1  | 2024/02/12 23:22:16 Account type  : free
warp-socks-1  | 2024/02/12 23:22:16 Role          : child
warp-socks-1  | 2024/02/12 23:22:16 Premium data  : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 Quota         : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Successfully created Cloudflare Warp account
warp-socks-1  | 2024/02/12 23:22:16 Using config file: wgcf-account.toml
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Device name   : 9CFD7F
warp-socks-1  | 2024/02/12 23:22:16 Device model  : PC
warp-socks-1  | 2024/02/12 23:22:16 Device active : true
warp-socks-1  | 2024/02/12 23:22:16 Account type  : free
warp-socks-1  | 2024/02/12 23:22:16 Role          : child
warp-socks-1  | 2024/02/12 23:22:16 Premium data  : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 Quota         : 0.00 B
warp-socks-1  | 2024/02/12 23:22:16 =======================================
warp-socks-1  | 2024/02/12 23:22:16 Successfully generated WireGuard profile: wgcf-profile.conf
warp-socks-1  | [#] ip link add warp type wireguard
warp-socks-1  | [#] wg setconf warp /dev/fd/63
warp-socks-1  | [#] ip -4 address add 172.16.0.2/32 dev warp
warp-socks-1  | [#] ip -6 address add 2606:4700:110:8572:30f3:d37c:e33b:71dd/128 dev warp
warp-socks-1  | [#] ip link set mtu 1280 up dev warp
warp-socks-1  | [#] resolvconf -a warp -m 0 -x
warp-socks-1  | [#] wg set warp fwmark 51820
warp-socks-1  | [#] ip -6 route add ::/0 dev warp table 51820
warp-socks-1  | [#] ip -6 rule add not fwmark 51820 table 51820
warp-socks-1  | [#] ip -6 rule add table main suppress_prefixlength 0
warp-socks-1  | [#] ip6tables-restore -n
warp-socks-1  | modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/5.15.0-202.135.2.el8uek.aarch64
warp-socks-1  | ip6tables-restore v1.8.4 (legacy): ip6tables-restore: unable to initialize table 'raw'
warp-socks-1  | 
warp-socks-1  | Error occurred at line: 1
warp-socks-1  | Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
warp-socks-1  | [#] resolvconf -d warp -f
warp-socks-1  | [#] ip -6 rule delete table 51820
warp-socks-1  | [#] ip -6 rule delete table main suppress_prefixlength 0

**Comment by Mon-ius** [comment]
It's the centos problem, for a temp solution see, https://github.com/Mon-ius/Docker-Warp-Socks/issues/22

**Comment by Mon-ius** [comment]
`Centos 7` is not support
