### ISSUE TITLE
Add support for external routes/devices

### ISSUE THREAD

**Issue by pranksta02** [Mon-ius/Docker-Warp-Socks#24]
Hi there,

Would it be possible to add support to add routes for non local traffic? ie I want to run the proxy on a different server to the server that is going to be using it which is in a completely different subnet?
At the moment on container start I need to then log in add manually add a route to my external subnet via:
ip route add x.x.x.x/x via 172.17.0.1 dev eth0
but it would be great if the container can have an env say ALLOWED_SUBNETS=x.x.x.x/x,x.x.y.y/y which are then added as routes on container start.

Thank you for your consideration, much appreciated.

**Comment by Mon-ius** [comment]
Hi pranksta02, 

Thanks for your advice, Would you like to submit a PR for this feature, I will review and merge it if possible 🤗

**Comment by pranksta02** [comment]
Thanks for the quick response, I have no idea how to make a pull request, time to start learning but for reference I would propose to just add the below to entrypoint.sh
```
if [ -n "$ALLOWED_SUBNETS" ]

    DEFAULT_GW=$(ip route | grep default | awk '{print $3}')

    IFS=',' read -r -a subnet_array <<< "$ALLOWED_SUBNETS"

    for subnet in "${subnet_array[@]}"
    do
        echo "Adding route for subnet: $subnet"
        ip route add "$subnet" via "$DEFAULT_GW"
    done

fi
```
I will try and figure out what a pull request is now and how to do it!

Cheers,

**Comment by Mon-ius** [comment]
Hi @pranksta02

It looks great, to be noticed that the current `v2` branch use `dash` aka `sh` as the default shell, not `bash`, plz make sure your script is compatible with `POSIX` shell, so I can perform a quick check to your proposal 🤗

**Comment by pranksta02** [comment]
Sorry my bad I didn't pick that up, in that case how about:
```
if [ -n "$ALLOWED_SUBNETS" ]

    DEFAULT_GW=$(ip route | grep default | awk '{print $3}')

    subnet_list=$(echo $ALLOWED_SUBNETS | tr ',' ' ')

    for subnet in $subnet_list
    do
        echo "Adding route for subnet: $subnet"
        ip route add "$subnet" via "$DEFAULT_GW"
    done

fi
```

**Comment by Mon-ius** [comment]
Cool, could u plz also add a corresponding test case for it? You can refer to "https://github.com/Mon-ius/Docker-Warp-Socks/blob/main/.github/workflows/verify_chain.yml".

**Comment by pranksta02** [comment]
Hi, sorry but I have no idea how to add a test, however I have manually added the below code to entrypoint.sh and can confirm it works exactly as expected
```
if [ -n "$ALLOWED_SUBNETS" ]; then

    DEFAULT_GW=$(ip route | grep default | awk '{print $3}')

    SUBNET_LIST=$(echo $ALLOWED_SUBNETS | tr ',' ' ')

    for subnet in $SUBNET_LIST
    do
        echo "Adding route for subnet: $subnet"
        ip route add "$subnet" via "$DEFAULT_GW"
    done

fi
```

**Comment by Mon-ius** [comment]
Can u submit a PR according to that?

**Comment by Mon-ius** [comment]
close due to no response
