### ISSUE TITLE
How to prioritize connections to ipv6 sites

### ISSUE THREAD

**Issue by SuperNG6** [Mon-ius/Docker-Warp-Socks#25]
Currently warp ipv4 addresses are being abused, I'm using the wireguard feature of singbox who supports prioritized ipv6 address resolution, and was wondering if [Docker-Warp-Socks](https://github.com/Mon-ius/Docker-Warp-Socks) supports prioritized ipv6 connections? Or is there any plan to consider supporting that feature?

<img width="401" alt="image" src="https://github.com/Mon-ius/Docker-Warp-Socks/assets/28585966/dc299b5a-5ba0-4013-bb3e-2a6449d30c49">

<img width="462" alt="image" src="https://github.com/Mon-ius/Docker-Warp-Socks/assets/28585966/5127299c-9dad-4ffc-baa1-a97d013b9949">

**Comment by Mon-ius** [comment]
@SuperNG6

Thanks for the advice, it can be added as the new feature to V2. Would u like to submit the PR and accelerate this process, I'm happy to merge it 🤗

**Comment by SuperNG6** [comment]
Thank you for your reply, I am not a programmer and not familiar with rust voice, sorry I can't contribute code to the project!

**Comment by Mon-ius** [comment]
Not sure if https://github.com/ViRb3/wgcf/issues/77 could answer your question
