### ISSUE TITLE
How many warp networks can a single server apply for? #6

### ISSUE THREAD

**Issue by johnsonwong666** [Mon-ius/Docker-Warp-Socks#26]
<img width="663" alt="image" src="https://github.com/aleskxyz/warp-svc/assets/64689255/eafb8630-c05c-476a-9273-5e851e5194f7">

Mar 11 10:34:10 (1710153250.679544) rws-cli[156]: info: block(1): tcp/accept ]: 172.28.0.1.48766 172.28.0.2.9091: error after 
reading 1 byte in 0 seconds: unknown SOCKS version 71 in client request

I am working with the other docker image to use. Is there a problem with this configuration?

<img width="553" alt="image" src="https://github.com/aleskxyz/warp-svc/assets/64689255/f64374f6-00ba-4287-9b66-8a1c4072ad2f">

**Comment by Mon-ius** [comment]
Please note, this project is designed exclusively for individual machine usage and is not intended for large-scale or abusive applications.
