### ISSUE TITLE
Resulting devices cgroup doesn't match target mode

### ISSUE THREAD

**Issue by notaLonelyDay** [Mon-ius/Docker-Warp-Socks#27]
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: resulting devices cgroup doesn't match target mode: unknown

because of privileged mode 
kernel 4.4.0

**Comment by Mon-ius** [comment]
The kernel is too old to have the correct Wireguard mod, try to upgrade it and try again

**Comment by notaLonelyDay** [comment]
@Mon-ius is it possible to run container not in privileged mode?
Because simple wg client can be run in docker. what should I disable?

**Comment by Mon-ius** [comment]
which wg client can be run inside docker container without privilege?

**Comment by notaLonelyDay** [comment]
@Mon-ius, This for example

https://github.com/linuxserver/docker-wireguard?tab=readme-ov-file#docker-compose-recommended-click-here-for-more-info

**Comment by Mon-ius** [comment]
well, you can have a try, just first generate the config use `Docker-Warp-Socks` and then map the config file to your given client. Don't forget to tell me if it works 🤗
