### ISSUE TITLE
[feature request] tailscale container integration

### ISSUE THREAD

**Issue by finzzz** [Mon-ius/Docker-Warp-Socks#28]
First of all, thank you for this great project!!

I'm not sure if it's possible to add integration with tailscale that acts as an exit node.
Basically the flow of traffic is as follows:
tailscale user => tailscale container => Docker-Warp-Socks using all_proxy env var => internet

Tailscale container and Docker-Warp-Socks are in the same machine
This doesn't work because tailscale container is also a VPN, I assume that's because of route table conflicts with this container..

**Comment by Mon-ius** [comment]
@E021ntox  Can u possible create a new issue and attach the details of the problem 🤗

**Comment by Mon-ius** [comment]
> First of all, thank you for this great project!!
> 
> I'm not sure if it's possible to add integration with tailscale that acts as an exit node. Basically the flow of traffic is as follows: tailscale user => tailscale container => Docker-Warp-Socks using all_proxy env var => internet
> 
> Tailscale container and Docker-Warp-Socks are in the same machine This doesn't work because tailscale container is also a VPN, I assume that's because of route table conflicts with this container..

Tailscale running on wireguard as well, I guess you possible want to have communication between two `IFACE`, if you can demostrate this feature, I am willing add it 🤗

**Comment by Mon-ius** [comment]
@E021ntox plz create another new issue due to your problem is not related to this topic

**Comment by finzzz** [comment]
I haven't got a time to look for more info, but I think we just need to exclude tailscale IP range from the warp.
So maybe this line https://github.com/Mon-ius/Docker-Warp-Socks/blob/main/dev/v1/entrypoint.sh#L45 we exclude 100.64.0.0/16 instead of routing everything.

**Comment by Mon-ius** [comment]
@finzzz Think just a little boy.

ANyway, if you can provide a quick demo, I can have it tested and add this feature very soon
