### ISSUE TITLE
WGCF_LICENSE_KEY doesn't work

### ISSUE THREAD

**Issue by pyt00n00b** [Mon-ius/Docker-Warp-Socks#30]
Setting WGCF_LICENSE_KEY="xxxxxxxx-xxxxxxxx-xxxxxxxx" results in broken installation.

Cmd used:
`docker run --privileged --restart=always -itd --name warp_socks_plus -e WGCF_LICENSE_KEY="xxxxxxxx-xxxxxxxx-xxxxxxxx" --cap-add NET_ADMIN --cap-add SYS_MODULE --sysctl net.ipv6.conf.all.disable_ipv6=0 --sysctl net.ipv4.conf.all.src_valid_mark=1 -v /lib/modules:/lib/modules -p 9091:9091 monius/docker-warp-socks`

No response from:
`curl -x socks5h://127.0.0.1:9091 -sL https://cloudflare.com/cdn-cgi/trace | grep warp`

While:
`docker run --privileged --restart=always -itd --name warp_socks --cap-add NET_ADMIN --cap-add SYS_MODULE --sysctl net.ipv6.conf.all.disable_ipv6=0 --sysctl net.ipv4.conf.all.src_valid_mark=1 -v /lib/modules:/lib/modules -p 9091:9091 monius/docker-warp-socks`

works.

**Comment by Mon-ius** [comment]
Hi, I noticed this issue about 5 weeks ago, thanks for report.

It may because the refer policy changes from cloudflare, that `LICENSE_KEY` from referenced account will not have the extra quota anymore.

**Comment by pyt00n00b** [comment]
In warp-cli the key works. In another repo like: aleskxyz/warp-svc it works.

Your implementation is the most stable I've come across. Thank you so much for this :)

Please find a way to make the key work again.

Regards.

**Comment by Mon-ius** [comment]
`@pyt00n00b`, the key works with both `aleskxyz/warp-svc` and `warp-cli`, which suggests that the algorithm may vary for `Plus` plan users.

I reviewed the source code of `aleskxyz/warp-svc`, and it indeed calls `warp-cli` internally, so it's no surprise that both tools function similarly.

However, `aleskxyz/warp-svc` does not support platforms like `arm`, `arm64`, `ppcle64`, and others. If you're using an `amd64` device, I recommend opting for the official solution, as outlined in https://github.com/Mon-ius/Docker-Warp-Socks#4-official-implement

**Comment by pyt00n00b** [comment]
I tried the official solution, but I can't access the host socks proxy exposed by warp+ from inside a docker container. Do you know a way? Thanks.

**Comment by Mon-ius** [comment]
no worries, will update v3 version soon.

**Comment by pyt00n00b** [comment]
Thank you so much!

**Comment by Mon-ius** [comment]
Closed due to `Cloudflare` public policy changes and related internal API changes. So the `Plus` will never shown anymore, see `https://support.cloudflarewarp.com/hc/en-us/articles/360025731413-How-do-I-subscribe-to-WARP-WARP-and-WARP-Unlimited`

**Comment by pyt00n00b** [comment]
Thanks so much for the new update. Much appreciated.

**Comment by ceozero** [comment]
> Closed due to `Cloudflare` public policy changes and related internal API changes. So the `Plus` will never shown anymore, see `https://support.cloudflarewarp.com/hc/en-us/articles/360025731413-How-do-I-subscribe-to-WARP-WARP-and-WARP-Unlimited`

Whether v3 supports plus keys. I added the key using-e WARP_LICENSE=$WARP_LICENSE, and after checking, siliver=none

**Comment by Mon-ius** [comment]
@ceozero the plus key can only support five devices, make sure you have valid plus key.

**Comment by krusherpt** [comment]
Tested v3 and latest with the right parameters, cannot get sliver=*-tier1, v2 works flawless. I think the new entrypoint is not taking the license.
