### ISSUE TITLE
run container failed

### ISSUE THREAD

**Issue by taylorwin** [Mon-ius/Docker-Warp-Socks#7]
2023/04/04 13:58:04 Using config file: wgcf-account.toml
2023/04/04 13:58:09 =======================================
2023/04/04 13:58:09 Device name   : DCDE62
2023/04/04 13:58:09 Device model  : PC
2023/04/04 13:58:09 Device active : true
2023/04/04 13:58:09 Account type  : free
2023/04/04 13:58:09 Role          : child
2023/04/04 13:58:09 Premium data  : 0.00 B
2023/04/04 13:58:09 Quota         : 0.00 B
2023/04/04 13:58:09 =======================================
2023/04/04 13:58:09 Successfully created Cloudflare Warp account
2023/04/04 13:58:09 Using config file: wgcf-account.toml
2023/04/04 13:58:10 =======================================
2023/04/04 13:58:10 Device name   : DCDE62
2023/04/04 13:58:10 Device model  : PC
2023/04/04 13:58:10 Device active : true
2023/04/04 13:58:10 Account type  : free
2023/04/04 13:58:10 Role          : child
2023/04/04 13:58:10 Premium data  : 0.00 B
2023/04/04 13:58:10 Quota         : 0.00 B
2023/04/04 13:58:10 =======================================
2023/04/04 13:58:10 Successfully generated WireGuard profile: wgcf-profile.conf
sed: -e expression #1, char 69: unknown command: `f'

**Comment by Mon-ius** [comment]
I see, you need to follow the given instructions to make the service active; 

I guess you may meet the same issue like Gib: 

`https://github.com/Mon-ius/Docker-Warp-Socks/issues/6#issuecomment-1497602912`

**Comment by Mon-ius** [comment]
Fix; https://github.com/Mon-ius/Docker-Warp-Socks/commit/92c1aadd837122fd046ba5992cb729606bc12261
