### ISSUE TITLE
readme中, 示例命令存在风险: 打开了一个没有密码保护的socks5端口

### ISSUE THREAD

**Issue by doggeddog** [Mon-ius/Docker-Warp-Socks#9]
最好修改为: -p 127.0.0.1:9091:9091 \

```
docker run --privileged --restart=always -itd \
    --name warp_socks \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --sysctl net.ipv4.conf.all.src_valid_mark=1 \
    --cap-add NET_ADMIN --cap-add SYS_MODULE \
    -p 127.0.0.1:9091:9091 \
    -v /lib/modules:/lib/modules \
    monius/docker-warp-socks
```

**Comment by Mon-ius** [comment]
Good to learn for windows user. Will test it in the ci/cl if it's universal for Linux as well

**Comment by Mon-ius** [comment]
I looked into your issue, the best practice is using your modified `danted.conf` as introduced in `1.2` to secure your socks5 connection, but it will lead to another question that not all tools suit using `user` and `password` for `socks5`, e.g.`SwitchyOmega`. So, I will put your suggestion on the `1.2` and `1.1` will remain simple and stupid to apply a easy start and test.

**Comment by Mon-ius** [comment]
I update the new feature today, check in `1.3` and try it out 🤗
